repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--length-sort", "--float-to-top", "--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: ["pep8-naming", "flake8-builtins"]
  #       args:
  #         [
  #           "--max-line-length=90",
  #           "--ignore=F401,E501,BLK100,E203 */__init__.py",
  #           "--extend-ignore=N815 */models/*.py",
  #         ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: debug-statements
      - id: check-docstring-first
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.2" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
